/**
 * @typedef {{ type: 'ox' | 'chest', value: number }} DailyQuestRewardType
 */

/**
 * /!\ Warning: This is not linked to the server side \
 * Server side data are in `src/Server/HTTP/src/data/dailyquest_rewards.php`
 * @type {Array<Array<DailyQuestRewardType>>}
 */
const DAILY_QUEST_REWARDS = [
    [{ type: 'ox', value: 1 }],
    [{ type: 'ox', value: 1 }],
    [{ type: 'ox', value: 1 }],
    [{ type: 'ox', value: 1 }],
    [{ type: 'ox', value: 1 }],
    [{ type: 'ox', value: 1 }],
    [{ type: 'ox', value: 1 }],
    [{ type: 'ox', value: 1 }],
    [{ type: 'ox', value: 1 }],
    [{ type: 'ox', value: 1 }],
    [{ type: 'ox', value: 1 }],
    [{ type: 'ox', value: 1 }],
    [{ type: 'ox', value: 1 }],
    [{ type: 'ox', value: 1 }],
    [{ type: 'ox', value: 1 }],
    [{ type: 'ox', value: 1 }],
    [{ type: 'ox', value: 1 }],
    [{ type: 'ox', value: 2 }, { type: 'chest', value: 0 }],
    [{ type: 'ox', value: 2 }],
    [{ type: 'ox', value: 2 }],
    [{ type: 'ox', value: 2 }],
    [{ type: 'ox', value: 2 }],
    [{ type: 'ox', value: 2 }],
    [{ type: 'ox', value: 2 }],
    [{ type: 'ox', value: 2 }],
    [{ type: 'ox', value: 2 }],
    [{ type: 'ox', value: 2 }],
    [{ type: 'ox', value: 2 }],
    [{ type: 'ox', value: 2 }],
    [{ type: 'ox', value: 2 }],
    [{ type: 'ox', value: 2 }],
    [{ type: 'ox', value: 2 }],
    [{ type: 'ox', value: 2 }],
    [{ type: 'ox', value: 2 }],
    [{ type: 'ox', value: 2 }],
    [{ type: 'ox', value: 3 }, { type: 'chest', value: 1 }],
    [{ type: 'ox', value: 3 }],
    [{ type: 'ox', value: 3 }],
    [{ type: 'ox', value: 3 }],
    [{ type: 'ox', value: 3 }],
    [{ type: 'ox', value: 3 }],
    [{ type: 'ox', value: 3 }],
    [{ type: 'ox', value: 3 }],
    [{ type: 'ox', value: 3 }],
    [{ type: 'ox', value: 3 }],
    [{ type: 'ox', value: 3 }],
    [{ type: 'ox', value: 3 }],
    [{ type: 'ox', value: 3 }],
    [{ type: 'ox', value: 3 }],
    [{ type: 'ox', value: 3 }],
    [{ type: 'ox', value: 3 }],
    [{ type: 'ox', value: 3 }],
    [{ type: 'ox', value: 3 }],
    [{ type: 'ox', value: 5 }, { type: 'chest', value: 2 }],
    [{ type: 'ox', value: 5 }],
    [{ type: 'ox', value: 5 }],
    [{ type: 'ox', value: 5 }],
    [{ type: 'ox', value: 5 }],
    [{ type: 'ox', value: 5 }],
    [{ type: 'ox', value: 5 }],
    [{ type: 'ox', value: 5 }],
    [{ type: 'ox', value: 5 }],
    [{ type: 'ox', value: 5 }],
    [{ type: 'ox', value: 5 }],
    [{ type: 'ox', value: 5 }],
    [{ type: 'ox', value: 5 }],
    [{ type: 'ox', value: 5 }],
    [{ type: 'ox', value: 5 }],
    [{ type: 'ox', value: 5 }],
    [{ type: 'ox', value: 5 }],
    [{ type: 'ox', value: 5 }],
    [{ type: 'ox', value: 5 }],
    [{ type: 'ox', value: 10 }, { type: 'chest', value: 3 }]
];

export default DAILY_QUEST_REWARDS;
