/**
 * @typedef {{ type: 'ox' | 'title' | 'chest', value: number }} NonZeroDayRewardType
 */

/** @type {Array<Array<NonZeroDayRewardType>>} */
const NONZERODAYS_REWARDS = [
    [{ type: 'ox', value: 1 }],
    [{ type: 'ox', value: 1 }],
    [{ type: 'ox', value: 1 }],
    [{ type: 'ox', value: 1 }],
    [{ type: 'ox', value: 1 }],
    [{ type: 'ox', value: 1 }],
    [{ type: 'ox', value: 1 }],
    [{ type: 'ox', value: 1 }],
    [{ type: 'ox', value: 1 }],
    [{ type: 'ox', value: 1 }],
    [{ type: 'ox', value: 1 }],
    [{ type: 'ox', value: 1 }],
    [{ type: 'ox', value: 1 }],
    [{ type: 'ox', value: 1 }],
    [{ type: 'ox', value: 1 }],
    [{ type: 'ox', value: 1 }],
    [{ type: 'ox', value: 1 }],
    [{ type: 'ox', value: 2 }, { type: 'chest', value: 1 }],
    [{ type: 'ox', value: 2 }],
    [{ type: 'ox', value: 2 }],
    [{ type: 'ox', value: 2 }],
    [{ type: 'ox', value: 2 }],
    [{ type: 'ox', value: 2 }],
    [{ type: 'ox', value: 2 }],
    [{ type: 'ox', value: 2 }],
    [{ type: 'ox', value: 2 }],
    [{ type: 'ox', value: 2 }],
    [{ type: 'ox', value: 2 }],
    [{ type: 'ox', value: 2 }],
    [{ type: 'ox', value: 2 }],
    [{ type: 'ox', value: 2 }],
    [{ type: 'ox', value: 2 }],
    [{ type: 'ox', value: 2 }],
    [{ type: 'ox', value: 2 }],
    [{ type: 'ox', value: 2 }],
    [{ type: 'ox', value: 3 }, { type: 'chest', value: 2 }],
    [{ type: 'ox', value: 3 }],
    [{ type: 'ox', value: 3 }],
    [{ type: 'ox', value: 3 }],
    [{ type: 'ox', value: 3 }],
    [{ type: 'ox', value: 3 }],
    [{ type: 'ox', value: 3 }],
    [{ type: 'ox', value: 3 }],
    [{ type: 'ox', value: 3 }],
    [{ type: 'ox', value: 3 }],
    [{ type: 'ox', value: 3 }],
    [{ type: 'ox', value: 3 }],
    [{ type: 'ox', value: 3 }],
    [{ type: 'ox', value: 3 }],
    [{ type: 'ox', value: 3 }],
    [{ type: 'ox', value: 3 }],
    [{ type: 'ox', value: 3 }],
    [{ type: 'ox', value: 3 }],
    [{ type: 'ox', value: 5 }, { type: 'chest', value: 3 }],
    [{ type: 'ox', value: 5 }],
    [{ type: 'ox', value: 5 }],
    [{ type: 'ox', value: 5 }],
    [{ type: 'ox', value: 5 }],
    [{ type: 'ox', value: 5 }],
    [{ type: 'ox', value: 5 }],
    [{ type: 'ox', value: 5 }],
    [{ type: 'ox', value: 5 }],
    [{ type: 'ox', value: 5 }],
    [{ type: 'ox', value: 5 }],
    [{ type: 'ox', value: 5 }],
    [{ type: 'ox', value: 5 }],
    [{ type: 'ox', value: 5 }],
    [{ type: 'ox', value: 5 }],
    [{ type: 'ox', value: 5 }],
    [{ type: 'ox', value: 5 }],
    [{ type: 'ox', value: 5 }],
    [{ type: 'ox', value: 5 }],
    [{ type: 'ox', value: 10 }, { type: 'chest', value: 4 }]
];

export default NONZERODAYS_REWARDS;
