/**
 * @typedef {{ type: 'ox' | 'chest', value: number }} NonZeroDayRewardType
 */

/**
 * /!\ Warning: This is not linked to the server side \
 * Server side data are in `src/Server/HTTP/src/Managers/NZD_rewards.php`
 * @type {Array<Array<NonZeroDayRewardType>>}
 */
const NONZERODAYS_REWARDS = [
    [{ type: 'ox', value: 1 }],
    [{ type: 'ox', value: 1 }],
    [{ type: 'ox', value: 1 }],
    [{ type: 'ox', value: 1 }],
    [{ type: 'ox', value: 1 }],
    [{ type: 'ox', value: 1 }],
    [{ type: 'ox', value: 1 }],
    [{ type: 'ox', value: 1 }],
    [{ type: 'ox', value: 1 }],
    [{ type: 'ox', value: 1 }],
    [{ type: 'ox', value: 1 }],
    [{ type: 'ox', value: 1 }],
    [{ type: 'ox', value: 1 }],
    [{ type: 'ox', value: 1 }],
    [{ type: 'ox', value: 1 }],
    [{ type: 'ox', value: 1 }],
    [{ type: 'ox', value: 1 }],
    [{ type: 'ox', value: 2 }, { type: 'chest', value: 1 }],
    [{ type: 'ox', value: 2 }],
    [{ type: 'ox', value: 2 }],
    [{ type: 'ox', value: 2 }],
    [{ type: 'ox', value: 2 }],
    [{ type: 'ox', value: 2 }],
    [{ type: 'ox', value: 2 }],
    [{ type: 'ox', value: 2 }],
    [{ type: 'ox', value: 2 }],
    [{ type: 'ox', value: 2 }],
    [{ type: 'ox', value: 2 }],
    [{ type: 'ox', value: 2 }],
    [{ type: 'ox', value: 2 }],
    [{ type: 'ox', value: 2 }],
    [{ type: 'ox', value: 2 }],
    [{ type: 'ox', value: 2 }],
    [{ type: 'ox', value: 2 }],
    [{ type: 'ox', value: 2 }],
    [{ type: 'ox', value: 3 }, { type: 'chest', value: 2 }],
    [{ type: 'ox', value: 3 }],
    [{ type: 'ox', value: 3 }],
    [{ type: 'ox', value: 3 }],
    [{ type: 'ox', value: 3 }],
    [{ type: 'ox', value: 3 }],
    [{ type: 'ox', value: 3 }],
    [{ type: 'ox', value: 3 }],
    [{ type: 'ox', value: 3 }],
    [{ type: 'ox', value: 3 }],
    [{ type: 'ox', value: 3 }],
    [{ type: 'ox', value: 3 }],
    [{ type: 'ox', value: 3 }],
    [{ type: 'ox', value: 3 }],
    [{ type: 'ox', value: 3 }],
    [{ type: 'ox', value: 3 }],
    [{ type: 'ox', value: 3 }],
    [{ type: 'ox', value: 3 }],
    [{ type: 'ox', value: 5 }, { type: 'chest', value: 3 }],
    [{ type: 'ox', value: 5 }],
    [{ type: 'ox', value: 5 }],
    [{ type: 'ox', value: 5 }],
    [{ type: 'ox', value: 5 }],
    [{ type: 'ox', value: 5 }],
    [{ type: 'ox', value: 5 }],
    [{ type: 'ox', value: 5 }],
    [{ type: 'ox', value: 5 }],
    [{ type: 'ox', value: 5 }],
    [{ type: 'ox', value: 5 }],
    [{ type: 'ox', value: 5 }],
    [{ type: 'ox', value: 5 }],
    [{ type: 'ox', value: 5 }],
    [{ type: 'ox', value: 5 }],
    [{ type: 'ox', value: 5 }],
    [{ type: 'ox', value: 5 }],
    [{ type: 'ox', value: 5 }],
    [{ type: 'ox', value: 5 }],
    [{ type: 'ox', value: 10 }, { type: 'chest', value: 4 }]
];

export default NONZERODAYS_REWARDS;
