name: 'GameLife - Continuous Deployment'

on:
  pull_request:
    branches:
      - prod
      - test

jobs:
  test:
    name: 'Application tests'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2

      - name: 'Setup Node.js'
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'

      - name: 'Cache NPM packages'
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-

      - name: 'Install Dependencies'
        run: npm install

      - name: 'Run tests'
        run: npm test

  deploy:
    runs-on: ubuntu-latest
    needs: [ test ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install FTP client
        run: sudo apt-get update && sudo apt-get install lftp -y

      - name: Upload files to FTP test server
        if: ${{ github.ref_name == 'test' }}
        run: lftp -c "open ftp://${{ secrets.FTP_TEST_USER }}:${{ secrets.FTP_TEST_PASS }}@${{ secrets.FTP_TEST_HOST }} && mirror --reverse ./src/Server/HTTP/"

      - name: Upload files to FTP prod server
        if: ${{ github.ref_name == 'prod' }}
        run: lftp -c "open ftp://${{ secrets.FTP_PROD_USER }}:${{ secrets.FTP_PROD_PASS }}@${{ secrets.FTP_PROD_HOST }} && mirror --reverse ./src/Server/HTTP/"
