name: GameLife - Continuous Deployment

on:
  pull_request:
    branches:
      - test
      - prod

jobs:
  test:
    name: Application tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Cache NPM packages
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-

      - name: Install Dependencies
        run: npm install

      - name: Run tests
        env:
          ENVFILE: .env.test
        run: npm test

  build:
    name: Build application
    runs-on: ubuntu-latest
    container: reactnativecommunity/react-native-android
    needs: [ test ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Cache NPM packages
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-

      - name: Install Dependencies
        run: npm install

      - name: Get config files
        run: |
          echo ${{ secrets.KEYSTORE }} | base64 -d > ./keystore
          echo ${{ secrets.APP_JSON }} | base64 -d > ./app.json
          echo ${{ secrets.ANDROID_KEYSTORE }} | base64 -d > ./android/app/gamelife.keystore

      - name: Build app
        env:
          ENVFILE: .env.${{ github.base_ref }}
        run: npm run build

      - name: Upload aab artifact
        uses: actions/upload-artifact@v3
        if: ${{ github.base_ref == 'prod' }}
        with:
          name: app-release.aab
          path: android/app/build/outputs/bundle/release/app-release.aab

      - name: Download buildtool
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip
          wget -O bundletool.jar https://github.com/google/bundletool/releases/download/1.15.0/bundletool-all-1.15.0.jar

      - name: Generate universal APK
        run: |
          java -jar ./bundletool.jar build-apks \
            --bundle=./android/app/build/outputs/bundle/release/app-release.aab \
            --output=my_app.apks \
            --mode=universal \
            --ks=./android/app/gamelife.keystore \
            --ks-key-alias=gameLifeAlias \
            --ks-pass=file:./keystore
          unzip -p my_app.apks universal.apk > GameLife-${{ github.base_ref }}.apk

      - name: Upload apk artifact
        uses: actions/upload-artifact@v3
        with:
          name: GameLife-${{ github.base_ref }}.apk
          path: GameLife-${{ github.base_ref }}.apk

  deploy:
    name: Deploy Server side
    runs-on: ubuntu-latest
    needs: [ build ]
    env:
      ARCHIVE: archive_code_$(date +'%Y-%m-%d_%H-%M-%S').tar.gz
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install FTP client
        run: sudo apt-get update && sudo apt-get install lftp tar -y

      - name: Create temporary directory
        run: mkdir -p ftp_backup

      - name: Download files from FTP test server
        if: ${{ github.base_ref == 'test' }}
        run: |
          lftp -c "set ftp:ssl-allow true; set ssl:verify-certificate no;
          open -u ${{ secrets.FTP_TEST_USER }},${{ secrets.FTP_TEST_PASS }} ${{ secrets.FTP_TEST_HOST }};
          mirror --exclude=backups/ / ftp_backup/"

      - name: Archive downloaded files
        if: ${{ github.base_ref == 'test' }}
        run: tar -czf ${{ env.ARCHIVE }} -C ftp_backup .

      - name: Upload archive to FTP test server
        if: ${{ github.base_ref == 'test' }}
        run: |
          lftp -c "set ftp:ssl-allow true; set ssl:verify-certificate no;
          open -u ${{ secrets.FTP_TEST_USER }},${{ secrets.FTP_TEST_PASS }} ${{ secrets.FTP_TEST_HOST }};
          put -O ./backups/ ${{ env.ARCHIVE }}"

      - name: Upload files to FTP test server
        if: ${{ github.base_ref == 'test' }}
        run: |
          lftp -c "set ftp:ssl-allow true; set ssl:verify-certificate no;
          open -u ${{ secrets.FTP_TEST_USER }},${{ secrets.FTP_TEST_PASS }} ${{ secrets.FTP_TEST_HOST }};
          mirror --reverse ./src/Server/HTTP/ /"

      - name: Download files from FTP prod server
        if: ${{ github.base_ref == 'prod' }}
        run: |
          lftp -c "set ftp:ssl-allow true; set ssl:verify-certificate no;
          open -u ${{ secrets.FTP_PROD_USER }},${{ secrets.FTP_PROD_PASS }} ${{ secrets.FTP_PROD_HOST }};
          mirror --exclude=backups/ / ftp_backup/"

      - name: Archive downloaded files
        if: ${{ github.base_ref == 'prod' }}
        run: tar -czf ${{ env.ARCHIVE }} -C ftp_backup .

      - name: Upload archive to FTP prod server
        if: ${{ github.base_ref == 'prod' }}
        run: |
          lftp -c "set ftp:ssl-allow true; set ssl:verify-certificate no;
          open -u ${{ secrets.FTP_PROD_USER }},${{ secrets.FTP_PROD_PASS }} ${{ secrets.FTP_PROD_HOST }};
          put -O ./backups/ ${{ env.ARCHIVE }}"

      - name: Upload files to FTP prod server
        if: ${{ github.base_ref == 'prod' }}
        run: |
          lftp -c "set ftp:ssl-allow true; set ssl:verify-certificate no;
          open -u ${{ secrets.FTP_PROD_USER }},${{ secrets.FTP_PROD_PASS }} ${{ secrets.FTP_PROD_HOST }};
          mirror --reverse ./src/Server/HTTP/ /"

  database:
    name: Database migration
    runs-on: ubuntu-latest
    needs: [ deploy ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install PHP with mysqli extension
        run: sudo apt-get update && sudo apt-get install php php-mysqli -y

      - name: Run migration - test
        if: ${{ github.base_ref == 'test' }}
        run: |
          php ./Tools/TableFusion/index.php \
          '${{ vars.DB_DEV_HOST }}' \
          '${{ vars.DB_DEV_USER }}' \
          '${{ secrets.DB_DEV_PASS }}' \
          '${{ vars.DB_DEV_NAME }}' \
          '${{ vars.DB_TEST_HOST }}' \
          '${{ vars.DB_TEST_USER }}' \
          '${{ secrets.DB_TEST_PASS }}' \
          '${{ vars.DB_TEST_NAME }}' \
          --no-confirm

      - name: Run migration - prod
        if: ${{ github.base_ref == 'prod' }}
        run: |
          php ./Tools/TableFusion/index.php \
          '${{ vars.DB_TEST_HOST }}' \
          '${{ vars.DB_TEST_USER }}' \
          '${{ secrets.DB_TEST_PASS }}' \
          '${{ vars.DB_TEST_NAME }}' \
          '${{ vars.DB_PROD_HOST }}' \
          '${{ vars.DB_PROD_USER }}' \
          '${{ secrets.DB_PROD_PASS }}' \
          '${{ vars.DB_PROD_NAME }}' \
          --no-confirm
