name: 'GameLife - Continuous Deployment'

on:
  pull_request:
    branches:
      - prod
      - test

jobs:
  test:
    name: 'Application tests'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2

      - name: 'Setup Node.js'
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'

      - name: 'Cache NPM packages'
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-

      - name: 'Install Dependencies'
        run: npm install

      - name: 'Run tests'
        run: npm test

  deploy:
    runs-on: ubuntu-latest
    needs: [ test ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set FTP variables
        env:
          FTP_HOST: ''
          FTP_USERNAME: ''
          FTP_PASSWORD: ''
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/test" ]]; then
            echo "Setting FTP variables for the test branch"
            echo "::set-env name=FTP_HOST::${{ secrets.FTP_TEST_HOST }}"
            echo "::set-env name=FTP_USERNAME::${{ secrets.FTP_TEST_USER }}"
            echo "::set-env name=FTP_PASSWORD::${{ secrets.FTP_TEST_PASS }}"
          elif [[ "${{ github.ref }}" == "refs/heads/prod" ]]; then
            echo "Setting FTP variables for the prod branch"
            echo "::set-env name=FTP_HOST::${{ secrets.FTP_PROD_HOST }}"
            echo "::set-env name=FTP_USERNAME::${{ secrets.FTP_PROD_USER }}"
            echo "::set-env name=FTP_PASSWORD::${{ secrets.FTP_PROD_PASS }}"
          fi

      - name: Upload files to FTP
        env:
          FTP_HOST: ${{ env.FTP_HOST }}
          FTP_USERNAME: ${{ env.FTP_USERNAME }}
          FTP_PASSWORD: ${{ env.FTP_PASSWORD }}
        run: |
          lftp -c "open ftp://example.com && mirror --reverse ./src/Server/HTTP/"

      - name: FTP Upload
        run: |
          # FTP installation
          sudo apt-get update
          sudo apt-get install ftp

          # Upload files
          put ./src/Server/HTTP/* ./
