name: 'GL Prod - Continuous Deployment'

on:
  workflow_dispatch:
    inputs:
      actions:
        description: 'Choose actions to do'
        required: true
        default: 'both'
        type: choice
        options:
        - both
        - deploy
        - migration

jobs:
  maintenance:
    name: 🚧 Enable Maintenance
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install PHP with mysqli extension
        run: sudo apt-get update && sudo apt-get install php php-mysqli -y

      - name: Enable maintenance mode - Test
        run: |
          php ./Tools/Maintenance/index.php \
            '${{ vars.DB_TEST_HOST }}' \
            '${{ vars.DB_TEST_USER }}' \
            '${{ secrets.DB_TEST_PASS }}' \
            '${{ vars.DB_TEST_NAME }}' \
            1

      - name: Enable maintenance mode - Prod
        run: |
          php ./Tools/Maintenance/index.php \
            '${{ vars.DB_PROD_HOST }}' \
            '${{ vars.DB_PROD_USER }}' \
            '${{ secrets.DB_PROD_PASS }}' \
            '${{ vars.DB_PROD_NAME }}' \
            1

  deploy:
    name: 🚀 Deploy Server side
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.actions == 'both' || github.event.inputs.actions == 'deploy' }}
    needs: maintenance
    env:
      ARCHIVE: archive_code_$(date +'%Y-%m-%d_%H-%M-%S').tar.gz
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install FTP client
        run: sudo apt-get update && sudo apt-get install lftp tar -y

      - name: Create temporary directory
        run: mkdir -p ftp_backup

      - name: Download files from FTP prod server
        run: |
          lftp -c "set ftp:ssl-allow true; set ssl:verify-certificate no;
          open -u ${{ secrets.FTP_TEST_USER }},${{ secrets.FTP_TEST_PASS }} ${{ secrets.FTP_TEST_HOST }};
          mirror --exclude=backups/ / ftp_backup/"

      - name: Archive downloaded files
        run: tar -czf ${{ env.ARCHIVE }} -C ftp_backup .

      - name: Upload archive to FTP prod server
        run: |
          lftp -c "set ftp:ssl-allow true; set ssl:verify-certificate no;
          open -u ${{ secrets.FTP_TEST_USER }},${{ secrets.FTP_TEST_PASS }} ${{ secrets.FTP_TEST_HOST }};
          put -O ./backups/ ${{ env.ARCHIVE }}"

      - name: Upload files to FTP prod server
        run: |
          lftp -c "set ftp:ssl-allow true; set ssl:verify-certificate no;
          open -u ${{ secrets.FTP_TEST_USER }},${{ secrets.FTP_TEST_PASS }} ${{ secrets.FTP_TEST_HOST }};
          mirror --reverse ./src/Server/HTTP/ /"

  migration:
    name: 🚚 Database migration
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.actions == 'both' || github.event.inputs.actions == 'migration' }}
    needs: maintenance
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install PHP with mysqli extension
        run: sudo apt-get update && sudo apt-get install php php-mysqli -y

      - name: Run migration - prod
        run: |
          php ./Tools/TableFusion/index.php \
          '${{ vars.DB_DEV_HOST }}' \
          '${{ vars.DB_DEV_USER }}' \
          '${{ secrets.DB_DEV_PASS }}' \
          '${{ vars.DB_DEV_NAME }}' \
          '${{ vars.DB_TEST_HOST }}' \
          '${{ vars.DB_TEST_USER }}' \
          '${{ secrets.DB_TEST_PASS }}' \
          '${{ vars.DB_TEST_NAME }}' \
          --no-confirm

  maintenance_off:
    name: 🚧 Disable Maintenance
    runs-on: ubuntu-latest
    needs: [deploy, migration]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install PHP with mysqli extension
        run: sudo apt-get update && sudo apt-get install php php-mysqli -y

      - name: Disable maintenance mode - Test
        run: |
          php ./Tools/Maintenance/index.php \
            '${{ vars.DB_TEST_HOST }}' \
            '${{ vars.DB_TEST_USER }}' \
            '${{ secrets.DB_TEST_PASS }}' \
            '${{ vars.DB_TEST_NAME }}' \
            0

      - name: Disable maintenance mode - Prod
        run: |
          php ./Tools/Maintenance/index.php \
            '${{ vars.DB_PROD_HOST }}' \
            '${{ vars.DB_PROD_USER }}' \
            '${{ secrets.DB_PROD_PASS }}' \
            '${{ vars.DB_PROD_NAME }}' \
            0
