name: '🧩 Update version'

on:
  workflow_call:
    inputs:
      action-update:
        description: 'Update app version (none, build, build-android, build-ios, patch, minor, major)'
        type: string
        required: true

jobs:
  update-version-prod:
    name: '📝 Update version - Prod'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
        with:
          ref: 'prod'

      - name: 'Update version'
        env:
          ACTION_UPDATE: ${{ github.event.inputs.action-update }}
        run: |
          NEWVERSION=$(./Tools/Version/version.sh $ACTION_UPDATE --version)
          echo "VERSION=$NEWVERSION" >> $GITHUB_ENV

          ./Tools/Version/version.sh $ACTION_UPDATE --force

      - name: 'Commit changes'
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git commit -m "📝 Update version to $VERSION"
          git push

  update-version-dev:
    name: '📝 Update version - Dev'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
        with:
          ref: 'dev'

      - name: 'Update version'
        env:
          ACTION_UPDATE: ${{ github.event.inputs.action-update }}
        run: |
          NEWVERSION=$(./Tools/Version/version.sh $ACTION_UPDATE --version)
          echo "VERSION=$NEWVERSION" >> $GITHUB_ENV

          ./Tools/Version/version.sh $ACTION_UPDATE --force

      - name: 'Commit changes'
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git commit -m "📝 Update version to $VERSION"
          git push
