name: '🧩 Update version'

on:
  workflow_call:
    inputs:
      action-update:
        description: 'Update app version (none, build, build-android, build-ios, patch, minor, major)'
        type: string
        required: true

jobs:
  update-versions:
    name: '📝 Update versions (Prod & Dev)'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 'Update version for both branches'
        env:
          ACTION_UPDATE: ${{ github.event.inputs.action-update }}
        run: |
          # Array of branches to update
          BRANCHES=("prod" "test" "dev")

          for BRANCH in "${BRANCHES[@]}"; do
            echo "Updating version for branch: $BRANCH"

            # Checkout branch
            git fetch origin $BRANCH
            git checkout $BRANCH

            # Update version
            NEWVERSION=$(./Tools/Version/version.sh $ACTION_UPDATE --version)
            echo "VERSION=$NEWVERSION" >> $GITHUB_ENV
            ./Tools/Version/version.sh $ACTION_UPDATE --force

            # Commit changes
            git config --local user.email "github-actions[bot]@users.noreply.github.com"
            git config --local user.name "github-actions[bot]"
            git add .
            git commit -m "📝 Update version to $NEWVERSION for branch $BRANCH"
            git push origin $BRANCH

            echo "Version updated for branch: $BRANCH"
          done
