name: '✋ GameLife - Continuous Delivery'

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Choose environment to build'
        required: true
        default: 'dev'
        type: choice
        options:
        - dev
        - test
        - prod
      actions:
        description: 'Choose platform to build'
        required: true
        default: 'none'
        type: choice
        options:
        - none
        - both
        - android
        - ios
      delivery:
        description: 'Delivery to stores (test & prod only)'
        required: true
        default: false
        type: boolean
      save-apk-artifact:
        description: 'Download apk artifact (android only)'
        required: false
        default: false
        type: boolean

jobs:
  tests:
    name: '🔍 Tests'
    uses: ./.github/workflows/step-tests.yml
    secrets: inherit
    with:
      environment: ${{ github.event.inputs.environment }}
      test-client: true
      test-resource: true
      test-tls-pinning: true

  android:
    name: '🤖 Android'
    needs: tests
    if: >
      always() &&
      (needs.tests.result == 'success') &&
      (
        github.event.inputs.actions == 'both' ||
        github.event.inputs.actions == 'android'
      )
    uses: ./.github/workflows/step-android.yml
    secrets: inherit
    with:
      environment: ${{ github.event.inputs.environment }}
      delivery: ${{ github.event.inputs.delivery == 'true' }}
      save-apk-artifact: ${{ github.event.inputs.save-apk-artifact == 'true' }}

  ios:
    name: '🍏 iOS'
    needs: tests
    if: >
      always() &&
      (needs.tests.result == 'success') &&
      (
        github.event.inputs.actions == 'both' ||
        github.event.inputs.actions == 'ios'
      )
    uses: ./.github/workflows/step-ios.yml
    secrets: inherit
    with:
      environment: ${{ github.event.inputs.environment }}
      delivery: ${{ github.event.inputs.delivery == 'true' }}
